site_name: Token Security Benchmark
site_description: Token Security Benchmark
repo_url: https://github.com/cryptousersecurity/token-security-benchmark
repo_name: token-security-benchmark
strict: true
theme:
  name: "material"
  language: en
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.superfences

nav:
  - Overview: index.md
  - TSB-2023-001 Honeypot: TSB-2023-001.md
  - TSB-2023-002 Mintable: TSB-2023-002.md
  - TSB-2023-003 OwnershipRetrieval: TSB-2023-003.md
  - TSB-2023-004 BalanceManipulation: TSB-2023-004.md
  - TSB-2023-005 HiddenOwnership: TSB-2023-005.md
  - TSB-2023-006 SelfDestruction: TSB-2023-006.md
  - TSB-2023-007 ExternalInvocation: TSB-2023-007.md
  - TSB-2023-008 BlackListFunction: TSB-2023-008.md
  - TSB-2023-009 FullSaleRestriction: TSB-2023-009.md
  - TSB-2023-010 SlippageModification: TSB-2023-010.md
  - TSB-2023-011 TransferPausable: TSB-2023-011.md
  - TSB-2023-012 PersonalSlippageModification: TSB-2023-012.md
  - TSB-2023-013 TransactionWhitelisting: TSB-2023-013.md
  - TSB-2023-014 AntiWhale: TSB-2023-014.md
  - TSB-2023-015 AntiWhaleModification: TSB-2023-015.md
  - TSB-2023-016 TradingCooldown: TSB-2023-016.md
